make protocol definition match implementation
com.badlogic.gdx.utils.GdxRuntimeException: java.lang.InternalError: Protocol method getActivateDescription: illegal argument (0) of type forge.game.card.CardView, java.lang.String expected
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:127)
Caused by: java.lang.InternalError: Protocol method getActivateDescription: illegal argument (0) of type forge.game.card.CardView, java.lang.String expected
	at forge.net.ProtocolMethod.checkArgs(ProtocolMethod.java:158)
	at forge.net.GameProtocolSender.sendAndWait(GameProtocolSender.java:21)
	at forge.net.client.NetGameController.sendAndWait(NetGameController.java:28)
	at forge.net.client.NetGameController.getActivateDescription(NetGameController.java:93)
	at forge.screens.match.views.VCardDisplayArea.getActivateAction(VCardDisplayArea.java:186)
	at forge.card.CardZoom.onCardChanged(CardZoom.java:113)
	at forge.card.CardZoom.show(CardZoom.java:64)
	at forge.screens.match.views.VCardDisplayArea$CardAreaPanel.showZoom(VCardDisplayArea.java:406)
	at forge.screens.match.views.VCardDisplayArea$CardAreaPanel.longPress(VCardDisplayArea.java:396)
	at forge.Forge$MainInputProcessor.longPress(Forge.java:575)
	at forge.toolbox.FGestureAdapter$1.run(FGestureAdapter.java:43)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.executeRunnables(LwjglApplication.java:246)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:199)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)

Signed-off-by: Jamin W. Collins <jamin.collins@gmail.com>